<a href="https://colab.research.google.com/github/raunakk07/Immersion-Batch-Preparation/blob/main/pythonBasics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Strings


In [ ]:
message = "Hello World"

print(message.lower())
print(message.upper())
print(message.count('l'))
print(message.find("World"))

new_m = message.replace("World" , "Beech")
print(new_m)

greet = "Hello"
name = "Michel"
#message = greet +" "+ name + ". Welcome!"

#message = "{}, {}. Welcome!".format(greet, name)

# conecpt of f strings
message = f"{greet}, {name.upper()}. Welcome!"
print(message)

hello world
HELLO WORLD
3
6
Hello Beech
Hello, MICHEL. Welcome!


In [ ]:
greet = 'Hello'
name = 'Michael'

print(dir(name))
print(help(str.endswith))

['__add__', '__class__', '__contains__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getnewargs__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mod__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__rmod__', '__rmul__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'capitalize', 'casefold', 'center', 'count', 'encode', 'endswith', 'expandtabs', 'find', 'format', 'format_map', 'index', 'isalnum', 'isalpha', 'isascii', 'isdecimal', 'isdigit', 'isidentifier', 'islower', 'isnumeric', 'isprintable', 'isspace', 'istitle', 'isupper', 'join', 'ljust', 'lower', 'lstrip', 'maketrans', 'partition', 'removeprefix', 'removesuffix', 'replace', 'rfind', 'rindex', 'rjust', 'rpartition', 'rsplit', 'rstrip', 'split', 'splitlines', 'startswith', 'strip', 'swapcase', 'title', 'translate', 'upper', 'zfill']
Help on method_descriptor:

endswit

#Boolean Variable


In [ ]:
type(True)
type(False)

bool

Boolean Functions


In [ ]:
my_str = "Harshit Srivastava"

print(my_str.isalnum())
print(my_str.isalpha())
print(my_str.isupper())
print(my_str.istitle())

#and so on
print(my_str.startswith('H'))
print(my_str.endswith('A'))

False
False
False
True
True
False


# Working with numerical data


In [ ]:
num = 3
print(type(num))
num2 = 3.4
print(type(num2))

# Arithmetic Operators:
# Addition :    3+2
# Subtractipon: 3-2
# Multiply:     3*2
# Division:     3/2
# Floor Division: 3//2
# Exponent:     3**2
#modulus:       3%2




<class 'int'>
<class 'float'>


#Functions

Instead of putting code Everywhere for same work we put specific tasks in a function so we can just call it everywhere else and if we need to change, we can just go to that function instead of searching for it in every code.

In [ ]:
def hello_func():
  pass #to just pass function for now but it won't throw any error for leaving it blank

print(hello_func())

None


In [ ]:
def hello_func():
  print("Hello function")
hello_func()

Hello function


In [ ]:
def hello_func():
  return "Hello Function"
print(hello_func().upper())

HELLO FUNCTION


In [ ]:
def hello_func(greeting):
  return "{} Function".format(greeting)

x = "random"
print(hello_func(x))

random Function


We don't really should know what's the content behind the function, we should just know what will be the output on the input.

Default value as argument in a Function

In [ ]:
def hello_func(greeting,name = 'You'):
  return f"{greeting} {name}"

greeting = "Good Evening"
person = "Harshit"

print(hello_func(greeting,person))
print(hello_func(greeting))

Good Evening Harshit
Good Evening You


In [ ]:
# All the star Argument is doing is allowing us to accept an arbitrary no of
# positional or keyword arguments

def student_info(*args , **kwargs):
  print(args)
  print(kwargs)

student_info('Math' , 'Art' , name = 'John' , age = 22)

# args is tuple with all of our positional arguments
# kwargs are a dictionary with all of our keyword and value pairs

('Math', 'Art')
{'name': 'John', 'age': 22}


In [5]:
def student_info(*args , **kwargs):
  print(args)
  print(kwargs)

courses = ["Math","Art"]
info = {'name' : 'John' , 'age' : 22}
student_info(courses,info)
student_info(*courses,**info)

(['Math', 'Art'], {'name': 'John', 'age': 22})
{}
('Math', 'Art')
{'name': 'John', 'age': 22}


In [ ]:
# Number of days per moth. First value placeholder for indexing purposes
month_days = [0,31,28,31,30,31,31,30,31,30,31]

def is_leap(year):
  """return true for leap years and false for non leap years"""
  return year%4 == 0 and (year%100 !=0 or year % 400 ==0)

def days_in_month(year,month):
  """Returns no of days in that month in that year"""

  if not 1<=month<=12:
    return "Invalid Month"
  if month ==2 and is_leap(year):
    return 29

  return month_days[month]



#NUMPY
Numpy is a genral-purpose array-processing package. It privides a high performance multidimensional array object, and tools for working with these arrays. It is fundamental package for scientific computing with Python

In [ ]:
import numpy as np

my_lst = [1,2,3,4,5]
arr = np.array(my_lst)
type(arr)
print(arr)

numpy.ndarray

In [ ]:
arr.shape

(5,)

In [ ]:
#multinested array
list1 = [1,2,4,6,7]
list2 = [3,2,4,5,1]
list3 = [8,4,3,2,9]

arr = np.array([list1,list2,list3])

arr

array([[1, 2, 4, 6, 7],
       [3, 2, 4, 5, 1],
       [8, 4, 3, 2, 9]])

In [ ]:
arr.shape

(3, 5)

In [ ]:
arr = arr.reshape(5,3)
print(arr)
arr.shape

[[1 2 4]
 [6 7 3]
 [2 4 5]
 [1 8 4]
 [3 2 9]]


(5, 3)