<a href="https://colab.research.google.com/github/raunakk07/Immersion-Batch-Preparation/blob/main/pythonBasics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Stings


In [10]:
message = "Hello World"

print(message.lower())
print(message.upper())
print(message.count('l'))
print(message.find("World"))

new_m = message.replace("World" , "Beech")
print(new_m)

hello world
HELLO WORLD
3
6
Hello Beech


#Boolean Variable


In [ ]:
type(True)
type(False)

bool

Boolean Functions


In [ ]:
my_str = "Harshit Srivastava"

print(my_str.isalnum())
print(my_str.isalpha())
print(my_str.isupper())
print(my_str.istitle())

#and so on
print(my_str.startswith('H'))
print(my_str.endswith('A'))

False
False
False
True
True
False


#NUMPY
Numpy is a genral-purpose array-processing package. It privides a high performance multidimensional array object, and tools for working with these arrays. It is fundamental package for scientific computing with Python

In [ ]:
import numpy as np

my_lst = [1,2,3,4,5]
arr = np.array(my_lst)
type(arr)
print(arr)

numpy.ndarray

In [ ]:
arr.shape

(5,)

In [ ]:
#multinested array
list1 = [1,2,4,6,7]
list2 = [3,2,4,5,1]
list3 = [8,4,3,2,9]

arr = np.array([list1,list2,list3])

arr

array([[1, 2, 4, 6, 7],
       [3, 2, 4, 5, 1],
       [8, 4, 3, 2, 9]])

In [ ]:
arr.shape

(3, 5)

In [ ]:
arr = arr.reshape(5,3)
print(arr)
arr.shape

[[1 2 4]
 [6 7 3]
 [2 4 5]
 [1 8 4]
 [3 2 9]]


(5, 3)